name: camera_recharger
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 3.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  google_ml_kit: ^0.13.0
  image_picker: ^0.8.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  built_value_generator: 8.4.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

